# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skill',
            field=models.CharField(max_length=15),
        ),
    ]
