# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20170627_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skill',
            field=models.CharField(choices=[('J', 'Junior'), ('I', 'Intermediate'), ('S', 'Senior')], default='I', max_length=1),
        ),
    ]
