# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 04:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_auto_20170627_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='job',
            name='skill',
            field=models.CharField(choices=[('J', 'Junior'), ('I', 'Intermediate'), ('S', 'Senior')], max_length=1),
        ),
    ]
