# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_auto_20170628_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employerId', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolId', models.IntegerField()),
                ('name', models.CharField(max_length=70)),
                ('coordinator', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField()),
                ('lastName', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=30)),
                ('schoolId', models.IntegerField()),
            ],
        ),
    ]
