# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 04:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0005_employer_school_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='employer',
            name='employerId',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='school',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='school',
            name='schoolId',
        ),
        migrations.RemoveField(
            model_name='student',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='schoolId',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentId',
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_graduation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_study',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='employer',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hub.Company'),
        ),
    ]
